export function ownerPage(): string {
  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>JAMA · 你的 AI 协作中心</title>
  <style>
    :root{--ink:#17211b;--muted:#68736c;--line:#dfe6e1;--paper:#f7f8f5;--card:#fff;--brand:#1f7a4d;--brand2:#dff3e7;--warn:#9a6200;--warnbg:#fff4d8;--danger:#a43c35;--dangerbg:#fde9e7;--blue:#275ea6;--bluebg:#eaf2ff;--shadow:0 12px 34px rgba(30,50,39,.08);--r:18px}
    *{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.5 Inter,"Segoe UI",system-ui,sans-serif}button,input,textarea,select{font:inherit;color:inherit}button{cursor:pointer}
    .app{min-height:100vh;display:grid;grid-template-columns:248px 1fr}.side{position:sticky;top:0;height:100vh;padding:24px 18px;background:#14251c;color:#eef7f1;display:flex;flex-direction:column}.brand{display:flex;align-items:center;gap:11px;padding:0 8px 26px}.brandmark{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;background:#b9f0ce;color:#173c26;font-weight:900;box-shadow:inset 0 0 0 1px rgba(255,255,255,.45)}.brand b{font-size:17px;letter-spacing:.2px}.brand small{display:block;color:#9db4a5;font-size:11px}
    nav{display:grid;gap:5px}.nav{width:100%;border:0;background:transparent;color:#aac0b1;border-radius:11px;padding:10px 12px;text-align:left;display:flex;align-items:center;gap:10px;font-weight:650}.nav:hover{background:#1b3225;color:#fff}.nav.active{background:#edf9f1;color:#173b27}.nav .ico{width:22px;text-align:center}.badge{margin-left:auto;min-width:20px;padding:1px 6px;border-radius:999px;background:#e3a62f;color:#241805;font-size:11px;text-align:center}.sidefoot{margin-top:auto;border-top:1px solid #2a4033;padding:17px 8px 0;color:#9db4a5}.statusline{display:flex;align-items:center;gap:8px}.dot{width:8px;height:8px;border-radius:50%;background:#58c884;box-shadow:0 0 0 4px rgba(88,200,132,.12)}
    .shell{min-width:0}.top{height:78px;padding:0 34px;border-bottom:1px solid var(--line);background:rgba(247,248,245,.92);backdrop-filter:blur(14px);display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:5}.top h1{margin:0;font-size:20px}.top p{margin:2px 0 0;color:var(--muted);font-size:12px}.actions{display:flex;gap:9px;align-items:center}.btn{border:1px solid var(--line);background:#fff;border-radius:10px;padding:8px 13px;font-weight:680;box-shadow:0 1px 1px rgba(0,0,0,.02)}.btn:hover{border-color:#b9c9bf;background:#fbfcfb}.btn.primary{background:var(--brand);border-color:var(--brand);color:#fff}.btn.primary:hover{background:#196841}.btn.danger{color:var(--danger);border-color:#edc8c5}.btn.ghost{background:transparent;box-shadow:none}.btn.small{padding:5px 9px;font-size:12px}.iconbtn{width:38px;height:38px;padding:0;border-radius:11px}
    main{padding:30px 34px 60px;max-width:1480px}.grid{display:grid;gap:16px}.metrics{grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:20px}.metric,.card{background:var(--card);border:1px solid var(--line);border-radius:var(--r);box-shadow:0 1px 0 rgba(24,40,31,.02)}.metric{padding:18px}.metric .label{color:var(--muted);font-size:12px}.metric .value{font-size:28px;font-weight:780;letter-spacing:-1px;margin-top:5px}.metric .hint{font-size:11px;color:var(--muted);margin-top:3px}.two{grid-template-columns:minmax(0,1.35fr) minmax(320px,.65fr)}.card{padding:20px}.cardhead{display:flex;align-items:flex-start;justify-content:space-between;gap:15px;margin-bottom:16px}.card h2,.card h3{margin:0}.card h2{font-size:16px}.card h3{font-size:14px}.sub{color:var(--muted);font-size:12px;margin-top:3px}.stack{display:grid;gap:10px}.row{display:flex;align-items:center;gap:12px}.between{justify-content:space-between}.grow{flex:1;min-width:0}.avatar{width:38px;height:38px;flex:none;border-radius:13px;background:var(--brand2);color:var(--brand);display:grid;place-items:center;font-weight:800}.avatar.blue{background:var(--bluebg);color:var(--blue)}
    .item{border:1px solid var(--line);border-radius:14px;padding:13px 14px;background:#fff}.item:hover{border-color:#c5d3ca}.item-title{font-weight:720}.meta{font-size:11px;color:var(--muted);margin-top:3px}.pill{display:inline-flex;align-items:center;gap:5px;padding:3px 8px;border-radius:999px;background:#edf1ee;color:#526159;font-size:11px;font-weight:700}.pill.green{background:var(--brand2);color:var(--brand)}.pill.yellow{background:var(--warnbg);color:var(--warn)}.pill.red{background:var(--dangerbg);color:var(--danger)}.pill.blue{background:var(--bluebg);color:var(--blue)}
    .notice{padding:15px;border-radius:14px;background:#eef6ff;border:1px solid #d6e7fb;display:flex;gap:12px;align-items:flex-start}.notice.warn{background:var(--warnbg);border-color:#f0dda8}.steps{counter-reset:step;display:grid;gap:10px}.step{display:flex;gap:12px;padding:13px;border-radius:13px;background:#f8faf8;border:1px solid var(--line)}.step:before{counter-increment:step;content:counter(step);width:26px;height:26px;flex:none;border-radius:50%;display:grid;place-items:center;background:#e8eee9;color:#5e6c63;font-weight:800}.step.done:before{content:"✓";background:var(--brand2);color:var(--brand)}
    .tabs{display:flex;gap:6px;margin-bottom:17px}.tab{border:0;background:transparent;color:var(--muted);padding:7px 10px;border-radius:9px;font-weight:650}.tab.active{background:#e8eee9;color:var(--ink)}.empty{text-align:center;border:1px dashed #cdd8d1;border-radius:16px;padding:34px 18px;color:var(--muted)}.empty strong{display:block;color:var(--ink);font-size:15px;margin-bottom:4px}
    .kanban{display:grid;grid-template-columns:repeat(3,minmax(250px,1fr));gap:14px;align-items:start}.column{background:#eef1ed;border-radius:16px;padding:12px;min-height:250px}.columnhead{display:flex;justify-content:space-between;padding:2px 3px 10px;font-weight:750}.column .item{margin-bottom:9px}.truncate{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mono{font:11px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:#5d6962}.people{grid-template-columns:repeat(auto-fill,minmax(260px,1fr))}.person{padding:18px}.person .avatar{width:46px;height:46px}.knowledge{grid-template-columns:repeat(auto-fill,minmax(300px,1fr))}.collection{padding:18px}.collection .bar{height:5px;border-radius:9px;background:#e9eeeb;margin:15px 0 12px;overflow:hidden}.collection .bar i{display:block;width:45%;height:100%;background:var(--brand)}
    dialog{width:min(620px,calc(100vw - 28px));border:0;border-radius:22px;padding:0;box-shadow:0 28px 90px rgba(10,25,16,.28)}dialog::backdrop{background:rgba(16,28,21,.48);backdrop-filter:blur(3px)}.modalhead{padding:21px 23px 14px;display:flex;justify-content:space-between}.modalhead h2{font-size:18px;margin:0}.modalbody{padding:6px 23px 22px;max-height:70vh;overflow:auto}.modalfoot{padding:15px 23px;border-top:1px solid var(--line);display:flex;justify-content:flex-end;gap:9px;background:#fafbfa}.close{border:0;background:#eef1ee;border-radius:9px;width:32px;height:32px;font-size:18px}.field{display:grid;gap:6px;margin:13px 0}.field label{font-size:12px;font-weight:720}.field input,.field textarea,.field select{width:100%;border:1px solid #cfd8d2;border-radius:10px;padding:10px 11px;background:#fff;outline:none}.field input:focus,.field textarea:focus,.field select:focus{border-color:#4b9a6d;box-shadow:0 0 0 3px rgba(54,139,91,.12)}.field textarea{min-height:90px;resize:vertical}.checkgrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.check{display:flex;align-items:flex-start;gap:8px;border:1px solid var(--line);border-radius:11px;padding:10px}.check input{width:auto;margin-top:3px}.help{font-size:11px;color:var(--muted)}
    .toast{position:fixed;right:24px;bottom:24px;max-width:360px;background:#17251d;color:#fff;border-radius:13px;padding:12px 15px;box-shadow:var(--shadow);z-index:20;transform:translateY(20px);opacity:0;pointer-events:none;transition:.2s}.toast.show{transform:none;opacity:1}.toast.error{background:#8a342f}.mobilebar{display:none}.skeleton{height:90px;border-radius:16px;background:linear-gradient(90deg,#edf0ed 25%,#f8faf8 37%,#edf0ed 63%);background-size:400% 100%;animation:shine 1.3s infinite}@keyframes shine{0%{background-position:100%}100%{background-position:0}}
    @media(max-width:980px){.app{grid-template-columns:82px 1fr}.side{padding:20px 11px}.brand{padding-left:10px}.brand div:last-child,.nav span:not(.ico),.sidefoot{display:none}.nav{justify-content:center;padding:11px}.badge{position:absolute;margin:-25px 0 0 25px}.metrics{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr}.kanban{grid-template-columns:1fr}}
    @media(max-width:650px){.app{display:block}.side{display:none}.top{height:68px;padding:0 17px}.top p{display:none}.top .actions .btn:not(.primary){display:none}main{padding:18px 14px 82px}.metrics{grid-template-columns:1fr 1fr;gap:10px}.metric{padding:14px}.metric .value{font-size:23px}.mobilebar{position:fixed;display:flex;bottom:0;left:0;right:0;background:#fff;border-top:1px solid var(--line);z-index:9;justify-content:space-around;padding:7px 4px env(safe-area-inset-bottom)}.mobilebar .nav{color:var(--muted);width:auto;display:grid;gap:0;padding:4px 10px;text-align:center;font-size:10px}.mobilebar .nav.active{color:var(--brand);background:transparent}.mobilebar .ico{font-size:17px}.checkgrid{grid-template-columns:1fr}}
  </style>
</head>
<body>
<div class="app">
  <aside class="side">
    <div class="brand"><div class="brandmark">J</div><div><b>JAMA</b><small>AI collaboration hub</small></div></div>
    <nav id="nav"></nav>
    <div class="sidefoot"><div class="statusline"><i class="dot"></i><span id="nodeStatus">本机网关在线</span></div><div class="mono truncate" id="nodeName">正在连接…</div></div>
  </aside>
  <div class="shell">
    <header class="top"><div><h1 id="pageTitle">今天</h1><p id="pageSubtitle">需要你关注的协作事项</p></div><div class="actions"><button class="btn iconbtn" onclick="refresh()" title="刷新">↻</button><button class="btn primary" onclick="quickCreate()">＋ 新建</button></div></header>
    <main id="root"><div class="grid metrics"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div></main>
  </div>
</div>
<div class="mobilebar" id="mobileNav"></div>
<dialog id="modal"><div class="modalhead"><div><h2 id="modalTitle"></h2><div class="sub" id="modalSub"></div></div><button class="close" onclick="closeModal()">×</button></div><form id="modalForm"><div class="modalbody" id="modalBody"></div><div class="modalfoot"><button class="btn" type="button" onclick="closeModal()">取消</button><button class="btn primary" id="modalSubmit" type="submit">继续</button></div></form></dialog>
<div class="toast" id="toast"></div>
<script>
const S={view:"home",health:{},cap:{},settings:{},identity:{},peers:[],approvals:[],sessions:[],tasks:[],providerAgents:[],providerJobs:[],collections:[],egress:[],writebacks:[],invites:[],groups:[],audit:{},loading:true};
const NAV=[['home','⌂','今天'],['inbox','✓','待处理'],['sessions','◉','会话'],['tasks','▦','任务'],['people','♙','联系人'],['knowledge','◇','知识库'],['settings','⚙','设置']];
const TITLES={home:['今天','需要你关注的协作事项'],inbox:['待处理','所有需要你决定的边界请求'],sessions:['会话','谁正在与你的 AI 协作'],tasks:['任务','跨 Agent 工作的进度与结果'],people:['联系人','已配对的人与他们的 AI'],knowledge:['知识库','明确选择哪些上下文可以被使用'],settings:['设置','网关状态、访问方式与安全边界']};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fmt(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?esc(v):new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function short(v){v=String(v||'');return v.length>15?v.slice(0,7)+'…'+v.slice(-5):v}
function statusLabel(v){return ({requested:'待确认',awaiting_owner_consent:'等待批准',active:'进行中',paused:'已暂停',revoked:'已撤销',expired:'已过期',closed:'已关闭',SUBMITTED:'待开始',WORKING:'进行中',COMPLETED:'已完成',FAILED:'失败',CANCELED:'已取消',INPUT_REQUIRED:'需要补充',pending:'待处理',approved:'已批准',denied:'已拒绝',consumed:'已使用'})[v]||v}
function pill(v){let c=['active','COMPLETED','approved','released','accepted'].includes(v)?'green':['requested','awaiting_owner_consent','pending','INPUT_REQUIRED','SUBMITTED'].includes(v)?'yellow':['revoked','FAILED','denied','rejected','CANCELED'].includes(v)?'red':'blue';return '<span class="pill '+c+'">'+esc(statusLabel(v))+'</span>'}
function empty(title,text,button){return '<div class="empty"><strong>'+esc(title)+'</strong>'+esc(text)+(button||'')+'</div>'}
function toast(msg,error){const el=document.getElementById('toast');el.textContent=msg;el.className='toast show'+(error?' error':'');clearTimeout(window.__toast);window.__toast=setTimeout(function(){el.className='toast'},3200)}
async function api(path,method,body){const r=await fetch(path,{method:method||'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let v;try{v=await r.json()}catch{v={error:'服务器返回了无法读取的响应'}}if(!r.ok)throw new Error(v.error||('请求失败 '+r.status));return v}
async function refresh(){S.loading=true;render();try{const paths=['/health','/api/capabilities','/api/settings','/api/identity','/api/peers','/api/approvals','/api/external-sessions','/api/tasks','/api/provider-agents','/api/provider-jobs','/api/context-collections','/api/egress-challenges','/api/writebacks','/api/session-invites','/api/groups','/api/audit/verify'];const values=await Promise.all(paths.map(function(p){return api(p)}));['health','cap','settings','identity','peers','approvals','sessions','tasks','providerAgents','providerJobs','collections','egress','writebacks','invites','groups','audit'].forEach(function(k,i){S[k]=values[i]});S.loading=false;render()}catch(e){S.loading=false;document.getElementById('root').innerHTML=empty('无法连接本机网关',e.message,'<br><button class="btn" onclick="refresh()">重试</button>');toast(e.message,true)}}
function pendingCount(){return S.approvals.filter(function(x){return x.status==='pending'}).length+S.sessions.filter(function(x){return ['requested','awaiting_owner_consent'].includes(x.status)}).length+S.egress.filter(function(x){return x.status==='pending'}).length+S.writebacks.filter(function(x){return x.status==='pending'}).length+S.providerAgents.filter(function(x){return x.status==='pending'}).length}
function renderNav(){const count=pendingCount();const html=NAV.map(function(n){return '<button class="nav '+(S.view===n[0]?'active':'')+'" onclick="setView(\\''+n[0]+'\\')"><span class="ico">'+n[1]+'</span><span>'+n[2]+'</span>'+(n[0]==='inbox'&&count?'<i class="badge">'+count+'</i>':'')+'</button>'}).join('');document.getElementById('nav').innerHTML=html;document.getElementById('mobileNav').innerHTML=html;document.getElementById('nodeName').textContent=(S.settings.name||'JAMA')+' · '+short(S.identity.peerId)}
function setView(v){S.view=v;render();window.scrollTo({top:0,behavior:'smooth'})}
function render(){renderNav();const t=TITLES[S.view]||TITLES.home;document.getElementById('pageTitle').textContent=t[0];document.getElementById('pageSubtitle').textContent=t[1];if(S.loading){document.getElementById('root').innerHTML='<div class="grid metrics"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>';return}const fn={home:homeView,inbox:inboxView,sessions:sessionsView,tasks:tasksView,people:peopleView,knowledge:knowledgeView,settings:settingsView}[S.view]||homeView;document.getElementById('root').innerHTML=fn()}
function metric(label,value,hint){return '<div class="metric"><div class="label">'+label+'</div><div class="value">'+value+'</div><div class="hint">'+hint+'</div></div>'}
function setupSteps(){const a=S.cap.canExecuteWork,c=S.collections.length>0,g=S.settings.guestInvitesEnabled,p=S.peers.length>0,pendingAgent=S.providerAgents.find(function(x){return x.status==='pending'});if(a&&c&&(g||p))return '';return '<div class="card" style="margin-bottom:20px"><div class="cardhead"><div><h2>把你的 AI 接入工作流</h2><div class="sub">只需要完成一次，以后从这里直接使用</div></div>'+pill(a?'active':'requested')+'</div><div class="steps"><div class="step '+(a?'done':'')+'"><div class="grow"><b>'+(a?'AI 已连接':pendingAgent?'确认连接 '+esc(pendingAgent.name):'连接一个可执行的 AI')+'</b><div class="sub">'+(a?'当前模式：'+esc(S.cap.adapter):pendingAgent?'这个 Agent 声明支持独立会话和跨重启恢复，请确认它属于你。':'Agent 安装 JAMA Provider Skill 后会自动出现在这里。')+'</div></div>'+(!a&&pendingAgent?'<button class="btn small primary" onclick="activateProvider(\\''+pendingAgent.id+'\\')">确认连接</button>':'')+'</div><div class="step '+(c?'done':'')+'"><div class="grow"><b>'+(c?'可共享知识已准备':'创建第一个知识空间')+'</b><div class="sub">明确选择可用于外部协作的信息，不开放全部记忆。</div></div>'+(c?'':'<button class="btn small" onclick="createCollection()">现在创建</button>')+'</div><div class="step '+((g||p)?'done':'')+'"><div class="grow"><b>'+((g||p)?'已有访问方式':'选择谁可以联系你的 AI')+'</b><div class="sub">给同事发邀请链接，或配对对方的 JAMA 网关。</div></div>'+((g||p)?'':'<button class="btn small" onclick="createInvite()">创建邀请</button>')+'</div></div></div>'}
function homeView(){const active=S.sessions.filter(function(x){return x.status==='active'});const running=S.tasks.filter(function(x){return ['WORKING','SUBMITTED','INPUT_REQUIRED'].includes(x.status)}).length+S.providerJobs.filter(function(x){return ['pending','claimed'].includes(x.status)}).length;const pending=pendingCount();const recent=S.sessions.slice(0,4);return setupSteps()+'<div class="grid metrics">'+metric('需要你处理',pending,pending?'有边界请求在等待决定':'当前没有待办')+metric('进行中的会话',active.length,'独立、可随时撤销')+metric('跨 AI 任务',running,'正在执行或等待补充')+metric('已连接的人',S.peers.length,'已验证并固定身份')+'</div><div class="grid two"><section class="card"><div class="cardhead"><div><h2>优先处理</h2><div class="sub">JAMA 只在真正需要你的判断时打扰你</div></div><button class="btn small" onclick="setView(\\'inbox\\')">查看全部</button></div>'+priorityItems()+'</section><section class="card"><div class="cardhead"><div><h2>最近会话</h2><div class="sub">你可以随时暂停或撤销</div></div></div><div class="stack">'+(recent.length?recent.map(sessionRow).join(''):empty('还没有会话','创建邀请，让同事直接问你的 AI。','<br><button class="btn small" onclick="createInvite()">创建邀请</button>'))+'</div></section></div>'}
function priorityItems(){let items=[];S.providerAgents.filter(function(x){return x.status==='pending'}).forEach(function(x){items.push('<div class="item row"><div class="avatar blue">AI</div><div class="grow"><div class="item-title">'+esc(x.name)+' 希望成为你的工作 Agent</div><div class="meta">支持持续会话：'+(x.capabilities.sessionResume?'是':'否')+' · 独立会话：'+(x.capabilities.isolatedSessions?'是':'否')+'</div></div><button class="btn small primary" onclick="activateProvider(\\''+x.id+'\\')">确认连接</button></div>')});S.sessions.filter(function(x){return ['requested','awaiting_owner_consent'].includes(x.status)}).forEach(function(x){items.push('<div class="item row"><div class="avatar">访</div><div class="grow"><div class="item-title">有人希望访问你的 AI</div><div class="meta">'+esc(x.purpose)+' · '+fmt(x.createdAt)+'</div></div><button class="btn small primary" onclick="approveSession(\\''+x.id+'\\')">查看并批准</button></div>')});S.approvals.filter(function(x){return x.status==='pending'}).forEach(function(x){items.push('<div class="item row"><div class="avatar blue">权</div><div class="grow"><div class="item-title">任务需要新的操作权限</div><div class="meta">'+esc(x.requestedScopes.join('、')||'受控操作')+' · '+fmt(x.createdAt)+'</div></div><button class="btn small primary" onclick="decideApproval(\\''+x.id+'\\',true)">批准</button><button class="btn small" onclick="decideApproval(\\''+x.id+'\\',false)">拒绝</button></div>')});S.egress.filter(function(x){return x.status==='pending'}).forEach(function(x){items.push('<div class="item row"><div class="avatar">出</div><div class="grow"><div class="item-title">一份回答在发送前等待确认</div><div class="meta">'+esc(x.reason||'输出边界确认')+'</div></div><button class="btn small primary" onclick="reviewEgress(\\''+x.id+'\\')">查看内容</button></div>')});S.writebacks.filter(function(x){return x.status==='pending'}).forEach(function(x){items.push('<div class="item row"><div class="avatar blue">记</div><div class="grow"><div class="item-title">是否把新信息写入知识库？</div><div class="meta">'+esc(x.proposedSummary)+'</div></div><button class="btn small primary" onclick="resolveWriteback(\\''+x.id+'\\',\\'accepted\\')">接受</button><button class="btn small" onclick="resolveWriteback(\\''+x.id+'\\',\\'rejected\\')">忽略</button></div>')});return '<div class="stack">'+(items.length?items.join(''):empty('今天很清静','没有审批、敏感输出或知识写回需要处理。'))+'</div>'}
function inboxView(){return '<div class="tabs"><button class="tab active">全部 '+pendingCount()+'</button><button class="tab">访问请求</button><button class="tab">操作权限</button><button class="tab">输出与写回</button></div><section class="card">'+priorityItems()+'</section>'}
function sessionRow(x){return '<div class="item row"><div class="avatar '+(x.callerType==='agent'?'blue':'')+'">'+(x.callerType==='agent'?'AI':'人')+'</div><div class="grow"><div class="item-title truncate">'+esc(x.purpose)+'</div><div class="meta">'+esc(x.callerTrust==='guest-capability'?'邀请访问':'已配对网关')+' · '+fmt(x.createdAt)+'</div></div>'+pill(x.status)+'</div>'}
function sessionsView(){const live=S.sessions.filter(function(x){return !['closed','revoked','expired'].includes(x.status)});const past=S.sessions.filter(function(x){return ['closed','revoked','expired'].includes(x.status)});function cards(list){return list.map(function(x){return '<div class="item"><div class="row"><div class="avatar '+(x.callerType==='agent'?'blue':'')+'">'+(x.callerType==='agent'?'AI':'人')+'</div><div class="grow"><div class="item-title">'+esc(x.purpose)+'</div><div class="meta">'+esc(x.callerPrincipalId)+' · 到期 '+fmt(x.expiresAt)+'</div></div>'+pill(x.status)+'</div><div class="row" style="margin-top:12px"><button class="btn small" onclick="sessionDetail(\\''+x.id+'\\')">查看对话</button>'+(['requested','awaiting_owner_consent'].includes(x.status)?'<button class="btn small primary" onclick="approveSession(\\''+x.id+'\\')">批准访问</button>':'')+(x.status==='active'?'<button class="btn small" onclick="sessionStatus(\\''+x.id+'\\',\\'paused\\')">暂停</button><button class="btn small danger" onclick="sessionStatus(\\''+x.id+'\\',\\'revoked\\')">撤销</button>':'')+(x.status==='paused'?'<button class="btn small primary" onclick="sessionStatus(\\''+x.id+'\\',\\'active\\')">恢复</button>':'')+'</div></div>'}).join('')}return '<div class="cardhead"><div><h2>正在协作</h2><div class="sub">每个会话都有独立目的、上下文和有效期</div></div><button class="btn primary" onclick="createInvite()">邀请同事</button></div><div class="grid two"><section class="card"><div class="cardhead"><h2>当前会话</h2><span class="pill green">'+live.length+'</span></div><div class="stack">'+(live.length?cards(live):empty('暂无进行中的会话','发一个邀请链接，对方无需安装 JAMA。'))+'</div></section><section class="card"><div class="cardhead"><h2>历史</h2><span class="pill">'+past.length+'</span></div><div class="stack">'+(past.length?cards(past):empty('暂无历史记录','完成或撤销的会话会出现在这里。'))+'</div></section></div>'}
function taskCard(x){const req=x.request||{};return '<div class="item"><div class="row between"><span class="pill blue">'+esc(x.mode||'task')+'</span><span class="meta">'+fmt(x.updatedAt)+'</span></div><div class="item-title" style="margin-top:9px">'+esc(req.objective||x.result?.answer||'跨 AI 任务')+'</div><div class="meta">对方 '+short(x.peerId)+' · '+short(x.id)+'</div><button class="btn small" style="margin-top:10px" onclick="taskDetail(\\''+x.id+'\\')">查看结果与责任记录</button></div>'}
function providerQueue(){if(!S.providerJobs.length)return '';return '<section class="card" style="margin-bottom:18px"><div class="cardhead"><div><h2>本机 Agent 工作队列</h2><div class="sub">Agent 自己完成工作，JAMA 只记录跨边界状态和结果</div></div><span class="pill">'+S.providerJobs.length+'</span></div><div class="stack">'+S.providerJobs.slice(0,8).map(function(x){return '<div class="item row"><div class="avatar blue">AI</div><div class="grow"><div class="item-title truncate">'+esc(x.request.prompt.slice(0,140))+'</div><div class="meta">第 '+x.attempt+' 次领取 · '+fmt(x.updatedAt)+(x.progress?' · '+esc(x.progress.message):'')+'</div></div>'+pill(x.status)+'</div>'}).join('')+'</div></section>'}
function tasksView(){const todo=S.tasks.filter(function(x){return ['SUBMITTED','INPUT_REQUIRED'].includes(x.status)}),doing=S.tasks.filter(function(x){return x.status==='WORKING'}),done=S.tasks.filter(function(x){return ['COMPLETED','FAILED','CANCELED','REJECTED'].includes(x.status)});function col(title,list){return '<div class="column"><div class="columnhead"><span>'+title+'</span><span class="pill">'+list.length+'</span></div>'+(list.length?list.map(taskCard).join(''):empty('没有任务',''))+'</div>'}return providerQueue()+'<div class="cardhead"><div><h2>跨 AI 任务板</h2><div class="sub">这里展示边界上的协作，不干涉 Agent 内部如何完成工作</div></div><button class="btn primary" onclick="askRemote()">找别人的 AI</button></div><div class="kanban">'+col('等待与补充',todo)+col('进行中',doing)+col('已完成',done)+'</div>'}
function peopleView(){return '<div class="cardhead"><div><h2>联系人与 AI</h2><div class="sub">连接后，你的 AI 可以在授权范围内直接找对方的 AI</div></div><button class="btn primary" onclick="addPeer()">添加联系人</button></div><div class="grid people">'+(S.peers.length?S.peers.map(function(p){return '<section class="card person"><div class="row"><div class="avatar">'+esc((p.name||'AI').slice(0,1).toUpperCase())+'</div><div class="grow"><h3>'+esc(p.name||'未命名 AI')+'</h3><div class="sub truncate">'+esc(p.url)+'</div></div><span class="pill green">已验证</span></div><div class="mono" style="margin-top:15px">'+esc(short(p.id))+'</div><div class="row" style="margin-top:14px"><button class="btn small primary" onclick="askRemote(\\''+p.id+'\\')">找 TA 的 AI</button><button class="btn small" onclick="copyText(\\''+esc(p.url)+'\\')">复制地址</button></div></section>'}).join(''):empty('还没有联系人','输入对方发给你的网关地址，即可完成身份验证与配对。','<br><button class="btn" onclick="addPeer()">添加第一个联系人</button>'))+'</div>'}
function knowledgeView(){return '<div class="cardhead"><div><h2>可共享知识</h2><div class="sub">只有这里明确登记的内容，才可能进入外部会话</div></div><button class="btn primary" onclick="createCollection()">新建知识空间</button></div><div class="grid knowledge">'+(S.collections.length?S.collections.map(function(c){return '<section class="card collection"><div class="row between"><div><h3>'+esc(c.name)+'</h3><div class="sub">'+esc(c.description||'没有描述')+'</div></div>'+pill(c.visibility==='private'?'paused':'active')+'</div><div class="bar"><i></i></div><div class="row between"><span class="pill">'+esc(c.defaultSensitivity)+'</span><span class="meta">最多 '+c.accessPolicy.maxItems+' 项 · '+c.accessPolicy.maxTokens+' tokens</span></div><div class="row" style="margin-top:14px"><button class="btn small" onclick="addKnowledge(\\''+c.id+'\\')">添加内容</button><button class="btn small" onclick="createInvite(\\''+c.id+'\\')">用它创建邀请</button></div></section>'}).join(''):empty('先创建一个知识空间','例如“项目 X 已确认决策”。JAMA 不会扫描你的整个磁盘或私人对话。','<br><button class="btn" onclick="createCollection()">创建知识空间</button>'))+'</div>'}
function settingsView(){const isolation=S.cap.isolationAssurance||'unknown';return '<div class="grid two"><section class="card"><div class="cardhead"><div><h2>访问方式</h2><div class="sub">让不懂 Agent 的同事也能直接使用</div></div></div><div class="item row"><div class="grow"><div class="item-title">邀请链接</div><div class="meta">允许你生成有时限、可撤销的访问链接</div></div><button class="btn '+(S.settings.guestInvitesEnabled?'primary':'')+'" onclick="toggleGuest()">'+(S.settings.guestInvitesEnabled?'已开启':'开启')+'</button></div><div class="item" style="margin-top:10px"><div class="item-title">公网入口</div><div class="mono truncate">'+esc(S.settings.publicUrl)+'</div><button class="btn small" style="margin-top:8px" onclick="copyText(\\''+esc(S.settings.publicUrl)+'\\')">复制</button></div></section><section class="card"><div class="cardhead"><div><h2>运行状态</h2><div class="sub">当前 AI 接入与安全保证</div></div>'+pill(S.health.ok?'active':'FAILED')+'</div><div class="stack"><div class="item row between"><span>执行接入</span><b>'+esc(S.cap.adapter||'—')+'</b></div><div class="item row between"><span>可执行工作</span><b>'+(S.cap.canExecuteWork?'是':'否')+'</b></div><div class="item row between"><span>会话隔离</span><b>'+esc(isolation)+'</b></div><div class="item row between"><span>审批策略</span><b>'+esc(S.cap.humanApproval||'—')+'</b></div></div></section><section class="card"><div class="cardhead"><div><h2>身份与审计</h2><div class="sub">本机身份不会因为界面简化而被隐藏</div></div></div><div class="field"><label>网关指纹</label><div class="mono">'+esc(S.identity.peerId)+'</div></div><div class="field"><label>审计链</label><div>'+pill(S.audit.valid?'active':'FAILED')+' <span class="meta">已验证 '+(S.audit.checked||0)+' 条记录</span></div></div></section><section class="card"><div class="cardhead"><div><h2>你的 AI 简介</h2><div class="sub">联系人发现你时看到的信息</div></div></div><div class="item"><div class="item-title">'+esc(S.cap.profile?.displayName||S.settings.name)+'</div><div class="meta">'+esc(S.cap.profile?.description||'')+'</div></div></section></div>'}
function modal(title,sub,html,label,handler){document.getElementById('modalTitle').textContent=title;document.getElementById('modalSub').textContent=sub||'';document.getElementById('modalBody').innerHTML=html;document.getElementById('modalSubmit').textContent=label||'继续';document.getElementById('modalForm').onsubmit=async function(e){e.preventDefault();const btn=document.getElementById('modalSubmit');btn.disabled=true;try{await handler(new FormData(e.target));closeModal();await refresh()}catch(err){toast(err.message,true)}finally{btn.disabled=false}};document.getElementById('modal').showModal()}
function closeModal(){document.getElementById('modal').close()}
function quickCreate(){modal('新建','你想从哪里开始？','<div class="stack"><button class="item row" type="button" onclick="closeModal();createInvite()"><span class="avatar">邀</span><span class="grow" style="text-align:left"><b>邀请同事问我的 AI</b><span class="sub" style="display:block">生成一个可直接打开的链接</span></span>›</button><button class="item row" type="button" onclick="closeModal();askRemote()"><span class="avatar blue">问</span><span class="grow" style="text-align:left"><b>找联系人的 AI</b><span class="sub" style="display:block">开始提问或交付任务</span></span>›</button><button class="item row" type="button" onclick="closeModal();createCollection()"><span class="avatar">知</span><span class="grow" style="text-align:left"><b>创建知识空间</b><span class="sub" style="display:block">选择可以用于协作的上下文</span></span>›</button></div>','关闭',async function(){})}
function createCollection(){modal('新建知识空间','先从一个明确的项目或主题开始。','<div class="field"><label>名称</label><input name="name" required placeholder="例如：Project X 已确认决策"></div><div class="field"><label>用途说明</label><textarea name="description" placeholder="这里包含什么，适合回答哪些问题"></textarea></div><div class="field"><label>默认敏感级别</label><select name="sensitivity"><option value="internal">内部</option><option value="public">公开</option><option value="confidential">机密</option><option value="restricted">严格受限</option></select></div><div class="field"><label>谁能发现</label><select name="visibility"><option value="invite-only">仅邀请</option><option value="paired-discoverable">已配对联系人</option><option value="private">仅自己</option></select></div>','创建',async function(f){await api('/api/context-collections','POST',{name:f.get('name'),description:f.get('description'),sourceType:'project-record',defaultSensitivity:f.get('sensitivity'),visibility:f.get('visibility'),accessPolicy:{allowedCallerTypes:['human','agent'],allowedTrust:['paired-gateway','guest-capability'],sensitivityCeiling:f.get('sensitivity'),exactContentAllowed:false,maxItems:8,maxTokens:6000,autoApprove:false}});toast('知识空间已创建')})}
function addKnowledge(id){modal('添加一条已确认知识','内容会保留来源，并且不会自动写入 Agent 私人记忆。','<div class="field"><label>简短结论</label><input name="summary" required placeholder="例如：发布环境统一使用 Node 22"></div><div class="field"><label>详细内容</label><textarea name="content" placeholder="补充依据、限制和相关背景"></textarea></div><div class="field"><label>敏感级别</label><select name="sensitivity"><option value="internal">内部</option><option value="public">公开</option><option value="confidential">机密</option></select></div>','添加',async function(f){await api('/api/context-collections/'+id+'/items','POST',{summary:f.get('summary'),content:f.get('content'),sensitivity:f.get('sensitivity'),authority:'owner-confirmed'});toast('已加入知识空间')})}
function collectionChecks(selected){return S.collections.map(function(c){return '<label class="check"><input type="checkbox" name="collections" value="'+esc(c.id)+'" '+(selected===c.id?'checked':'')+'><span><b>'+esc(c.name)+'</b><span class="help" style="display:block">'+esc(c.description||c.defaultSensitivity)+'</span></span></label>'}).join('')}
function createInvite(selected){if(!S.settings.guestInvitesEnabled){modal('开启邀请链接','邀请默认关闭。开启后，每个链接仍然有独立权限、有效期，并可随时撤销。','<div class="notice warn"><span>🔐</span><div><b>不会开放你的全部 AI</b><div class="sub">链接只允许访问你选择的知识空间和操作。</div></div></div>','开启并继续',async function(){await api('/api/settings','PUT',{guestInvitesEnabled:true});toast('邀请链接已开启');setTimeout(function(){createInvite(selected)},250)});return}modal('邀请同事','对方打开链接即可使用，不需要安装 Agent。','<div class="field"><label>这次协作的目的</label><input name="purpose" required placeholder="例如：确认 Project X 的历史设计决策"></div><div class="field"><label>允许使用的知识空间</label><div class="checkgrid">'+(S.collections.length?collectionChecks(selected):'<div class="notice warn">还没有知识空间。可以先发起不含背景资料的会话。</div>')+'</div></div><div class="field"><label>允许做什么</label><div class="checkgrid"><label class="check"><input type="checkbox" name="actions" value="ask" checked>提问与澄清</label><label class="check"><input type="checkbox" name="actions" value="task">交付受控任务</label></div></div><div class="field"><label>最长会话时间</label><select name="lease"><option value="3600">1 小时</option><option value="28800" selected>8 小时</option><option value="86400">1 天</option><option value="604800">7 天</option></select></div>','生成邀请链接',async function(f){const result=await api('/api/session-invites','POST',{purpose:f.get('purpose'),collectionIds:f.getAll('collections'),allowedActions:f.getAll('actions'),sensitivityCeiling:'internal',mode:'request-only',maxSessionSeconds:Number(f.get('lease'))});await copyText(result.url);setTimeout(function(){showInvite(result.url)},250)})}
function showInvite(url){modal('邀请已准备好','链接已复制，可以直接发给同事。','<div class="notice"><span>✓</span><div class="grow"><b>对方无需安装任何东西</b><div class="sub">打开链接、说明身份，然后等待你的批准。</div></div></div><div class="field"><label>邀请链接</label><input value="'+esc(url)+'" readonly onclick="this.select()"></div>','完成',async function(){})}
async function toggleGuest(){await api('/api/settings','PUT',{guestInvitesEnabled:!S.settings.guestInvitesEnabled});toast(S.settings.guestInvitesEnabled?'邀请链接已关闭':'邀请链接已开启');refresh()}
function addPeer(){modal('添加联系人','输入对方 JAMA 页面显示的网关地址。JAMA 会读取并固定其身份指纹。','<div class="field"><label>联系人名称</label><input name="name" required placeholder="例如：Alice 的 AI"></div><div class="field"><label>对方网关地址</label><input name="url" type="url" required placeholder="http://192.168.1.46:43120"></div><div class="notice"><span>⌁</span><div><b>首次连接会校验身份</b><div class="sub">之后身份发生变化时会拒绝连接，而不是静默信任。</div></div></div>','验证并添加',async function(f){await api('/api/peers','POST',{name:f.get('name'),url:f.get('url')});toast('联系人已验证并添加')})}
function askRemote(peerId){if(!S.peers.length){addPeer();return}const options=S.peers.map(function(p){return '<option value="'+esc(p.id)+'" '+(peerId===p.id?'selected':'')+'>'+esc(p.name)+'</option>'}).join('');modal('找别人的 AI','先说明目的。对方只会提供 Owner 允许的上下文。','<div class="field"><label>联系人</label><select name="peer">'+options+'</select></div><div class="field"><label>目的</label><input name="purpose" required placeholder="例如：澄清上周方案为什么被放弃"></div><div class="field"><label>第一条消息</label><textarea name="message" required placeholder="直接描述你想知道或想完成的事情"></textarea></div>','发送请求',async function(f){const opened=await api('/api/remote-external-sessions','POST',{peerId:f.get('peer'),purpose:f.get('purpose'),collectionIds:[],exactContentAllowed:false,allowedActions:['ask','task']});if(opened.session&&opened.session.status==='active'){await api('/api/remote-external-sessions/'+opened.session.id+'/messages','POST',{peerId:f.get('peer'),message:f.get('message'),operation:'ask'});toast('消息已发送')}else{toast('访问请求已发送，等待对方批准')}})}
async function decideApproval(id,yes){try{await api('/api/approvals/'+id+'/'+(yes?'approve':'deny'),'POST',{});toast(yes?'权限已批准':'权限已拒绝');refresh()}catch(e){toast(e.message,true)}}
async function activateProvider(id){try{await api('/api/provider-agents/'+id+'/activate','POST',{});toast('你的 AI 已连接，可以接收持续会话');refresh()}catch(e){toast(e.message,true)}}
async function suspendProvider(id){try{await api('/api/provider-agents/'+id+'/suspend','POST',{});toast('Agent 已暂停，不会领取新的工作');refresh()}catch(e){toast(e.message,true)}}
async function approveSession(id){try{const d=await api('/api/external-sessions/'+id);const r=d.requestedGrant;modal('批准这次访问','检查目的和范围。你可以在批准后随时暂停或撤销。','<div class="notice"><div><b>'+esc(d.session.purpose)+'</b><div class="sub">来自 '+esc(d.session.callerTrust==='guest-capability'?'邀请访客':'已配对联系人')+'</div></div></div><div class="field"><label>允许使用的知识空间</label><div class="checkgrid">'+S.collections.map(function(c){return '<label class="check"><input type="checkbox" name="collections" value="'+esc(c.id)+'" '+(r.requestedCollections.includes(c.id)?'checked':'')+'>'+esc(c.name)+'</label>'}).join('')+'</div></div><div class="field"><label>有效范围</label><div class="help">最多 '+r.requestedLimits.maxItems+' 条上下文、'+r.requestedLimits.maxTokens+' tokens；不允许原文精确引用。</div></div>','批准访问',async function(f){await api('/api/external-sessions/'+id+'/approve','POST',{allowedCollections:f.getAll('collections'),sensitivityCeiling:r.requestedSensitivity,exactContentAllowed:false,maxItems:r.requestedLimits.maxItems,maxTokens:r.requestedLimits.maxTokens,allowedOperations:d.operationGrant.allowedOperations,actionScopes:[],deniedScopes:[],allowedResources:[],deniedResources:[],actionApprovalRule:'runtime-policy'});toast('会话已批准')})}catch(e){toast(e.message,true)}}
async function sessionStatus(id,status){try{if(status==='active'){await approveSession(id)}else{await api('/api/external-sessions/'+id+'/status','POST',{status:status});toast(status==='revoked'?'访问已撤销':'会话状态已更新');refresh()}}catch(e){toast(e.message,true)}}
async function sessionDetail(id){try{const d=await api('/api/external-sessions/'+id);const events=(d.events||[]).map(function(e){return '<div class="item"><div class="row between"><b>'+esc(e.type==='caller-message'?'对方':e.type==='agent-message'?'你的 AI':statusLabel(e.type))+'</b><span class="meta">'+fmt(e.createdAt)+'</span></div><div style="margin-top:7px">'+esc(typeof e.content==='string'?e.content:JSON.stringify(e.content||{}))+'</div></div>'}).join('');modal(d.session.purpose,'独立 External Session · '+statusLabel(d.session.status),events||empty('还没有消息','会话批准后，对方的消息会出现在这里。'),'关闭',async function(){})}catch(e){toast(e.message,true)}}
async function taskDetail(id){try{const t=await api('/api/tasks/'+id);const audit=await api('/api/audit?taskId='+encodeURIComponent(id));modal('任务详情',statusLabel(t.status)+' · '+short(t.id),'<div class="field"><label>任务</label><div class="item">'+esc(t.request?.objective||'跨 AI 任务')+'</div></div><div class="field"><label>结果</label><div class="item">'+esc(JSON.stringify(t.result||{},null,2))+'</div></div><div class="field"><label>责任记录</label><div class="stack">'+audit.map(function(a){return '<div class="item row between"><span>'+esc(a.action)+'</span><span class="meta">'+fmt(a.timestamp)+'</span></div>'}).join('')+'</div></div>','关闭',async function(){})}catch(e){toast(e.message,true)}}
function reviewEgress(id){const x=S.egress.find(function(v){return v.id===id});if(!x)return;modal('发送前确认',x.reason||'这份回答可能触及输出边界','<div class="field"><label>准备发送的内容</label><div class="item" style="white-space:pre-wrap">'+esc(typeof x.draft==='string'?x.draft:JSON.stringify(x.draft,null,2))+'</div></div>','允许发送',async function(){await api('/api/egress-challenges/'+id+'/resolve','POST',{decision:'released',draftDigest:x.draftDigest});toast('回答已发送')})}
async function resolveWriteback(id,decision){try{await api('/api/writebacks/'+id+'/resolve','POST',{decision:decision});toast(decision==='accepted'?'已写入知识库':'已忽略写回');refresh()}catch(e){toast(e.message,true)}}
async function copyText(v){try{await navigator.clipboard.writeText(v);toast('已复制')}catch{const ta=document.createElement('textarea');ta.value=v;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('已复制')}}
refresh();
</script>
</body></html>`;
}
